[project]
name = "kodaflux"
version = "0.0.0"
requires-python = ">=3.12"
readme = "README.md"
dependencies = ["agent", "backend"]

[dependency-groups]
dev = [
    "pathspec>=1.0.4",
    "ruff>=0.15.5",
]

[tool.uv.sources]
backend = { workspace = true }
agent = { workspace = true }

[tool.uv.workspace]
members = ["packages/agent", "packages/backend"]
exclude = ["packages/frontend"]
