import re
import os

import httpx

from lib.storage_provider import StorageProvider
from state import AgentState


def slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def build_index(project_name: str, docs: list[dict]) -> str:
    links = "\n".join(f"- [{d['name']}](docs/{slugify(d['name'])}.md)" for d in docs)
    return f"# {project_name}\n\nAuto-generated by Kodaflux.\n\n## Dependencies\n\n{links}\n"


def build_sidebar(project_name: str, docs: list[dict]) -> str:
    links = "\n".join(f"  - [{d['name']}](docs/{slugify(d['name'])}.md)" for d in docs)
    return f"- [Home](/)\n- **{project_name}**\n{links}\n"


def build_index_html(project_name: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>{project_name} Docs</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsify@4/lib/themes/vue.css" />
</head>
<body>
  <div id="app"></div>
  <script>
    window.$docsify = {{
      name: '{project_name}',
      loadSidebar: true,
      subMaxLevel: 2,
      auto2top: true,
      search: {{ placeholder: 'Search docs' }},
    }}
  </script>
  <script src="https://cdn.jsdelivr.net/npm/docsify@4"></script>
  <script src="https://cdn.jsdelivr.net/npm/docsify@4/lib/plugins/search.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/prismjs@1/components/prism-bash.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/prismjs@1/components/prism-python.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/prismjs@1/components/prism-typescript.min.js"></script>
</body>
</html>"""


async def storer(state: AgentState) -> AgentState:
    project = state["project_name"]
    repo_url = state["repo_url"]
    site_url = state.get("site_url", "")
    dependencies = state.get("dependencies", [])
    docs = state.get("docs_url_content", [])
    storage = StorageProvider()

    # Initialies files with template files & their content
    files: dict[str, str] = {
        f"{project}/index.html": build_index_html(project),
        f"{project}/.nojekyll": "",
        f"{project}/README.md": build_index(project, docs),
        f"{project}/_sidebar.md": build_sidebar(project, docs),
    }

    # One markdown file per dep under /docs
    for dep in docs:
        slug = slugify(dep["name"])
        files[f"{project}/docs/{slug}.md"] = dep["markdown"]

    # Write everything to Spaces
    _urls = storage.write_many(files)
    site_url = storage.get_project_url(project)

    # Signal completion to the backend
    callback_url = os.getenv("COMPLETION_CALLBACK_URL")
    if callback_url:
        async with httpx.AsyncClient() as client:
            await client.post(
                callback_url,
                json={
                    "project_name": project,
                    "repo_url": repo_url,
                    "site_url": site_url,
                    "dependencies": dependencies,
                    "status": "complete",
                },
                timeout=10,
            )

    return {**state, "stored": True, "site_url": site_url}
