name: KodaFlux CI/CD Workflow

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  # Detects changes in app and infrastructure packages
  changes:
    runs-on: ubuntu-latest
    # Only check for changes when:
    # - Event is either push, pull_request or workflow_dispatch
    # - Does not contain "[skipci]" in commit message
    if: ${{ (github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch') && !(contains(github.event.commits.message, '[skipci]')) }}
    outputs:
      agent: ${{ steps.filter.outputs.agent }}
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      infrastructure: ${{ steps.filter.outputs.infrastructure }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'packages/backend/**'
            frontend:
              - 'packages/frontend/**'
            agent:
              - 'packages/agent/**'
            infrastructure:
              - 'infrastructure/**'

  # Runs project-wide linting
  lint:
    needs: [changes]
    # Only run linting when:
    # - Event is not "workflow_dispatch"
    # - Event is either push or pull request
    # - Does not contain "[skipci]" in the commit message
    if: ${{ github.event_name != 'workflow_dispatch' && ((github.event_name == 'push' || github.event_name == 'pull_request') && !(contains(github.event.commits.message, '[skipci]'))) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-tools

      # Runs `uv sync` as part of "prepare" script
      - name: PNPM Install & UV Sync
        run: |
          pnpm install --frozen-lockfile
          uv sync --frozen

      - name: Run project-wide linters
        run: turbo run lint

  # Runs project-wide test suites
  test:
    needs: [changes]
    runs-on: ubuntu-latest
    # Only run tests when:
    # - Event is either a push, pull_request or workflow_dispatch
    # - Does not contain "[skipci]" in the commit message
    if: ${{ (github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch') && !(contains(github.event.commits.message, '[skipci]')) }}
    steps:
      - uses: actions/checkout@v6

      - name: Run tests
        run: echo "Tests to be implemented once the hackathon submission is done. No new features."

  # Builds and pushes docker images for frontend & backend packages
  #
  # Successfully built images will be pushed to DOCR and an auto-deployment will be triggered
  build-and-push:
    needs: [lint, test, changes]
    runs-on: ubuntu-latest
    # Only run tests when:
    # - Event is either a push, pull_request or workflow_dispatch
    # - Does not contain "[skipci]" in the commit message
    if: ${{ (github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch') && !(contains(github.event.commits.message, '[skipci]')) }}
    permissions:
      packages: write
    strategy:
      fail-fast: true
      matrix:
        include:
          - app-name: frontend
            should-build: ${{ needs.changes.outputs.frontend == 'true' }}
            dockerfile: ./packages/frontend/Dockerfile
          - app-name: backend
            should-build: ${{ needs.changes.outputs.backend == 'true' }}
            dockerfile: ./packages/backend/Dockerfile
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/build-docker-images
        if: ${{ (matrix.should-build && github.event_name == 'push' && github.ref_name == 'main') || (github.event_name == 'workflow_dispatch') }}
        with:
          actor: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          app-name: ${{ matrix.app-name }}
          dockerfile-path: ${{ matrix.dockerfile }}
          digitalocean-email: ${{ secrets.DO_REGISTERED_EMAIL }}
          digitalocean-access-token: ${{ secrets.TF_VAR_DO_TOKEN }}
